/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 15:18:12 GMT 2022
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Library;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      try { 
        library0.addProfMember("uyzt2p=L");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Member with the same name exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 1, 478, 1);
      try { 
        library0.addBook("uyzt2p=L", 1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document with the same title exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 1, 1287, 1);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      try { 
        library0.extend("uyzt2p=L", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 1, 1287, 1);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      try { 
        library0.returnDocument("Xl2D)", "ir.ramtung.impl1.CannotExtendEx");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 18, 18, 18);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      library0.addProfMember("XliD)");
      int int0 = library0.getTotalPenalty("XliD)");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 18, 18, 18);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      int int0 = library0.getTotalPenalty("uyzt2p=L");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.timePass((-10));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot go back in time
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Library library0 = new Library();
      library0.timePass(558);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.getTotalPenalty("uj&0~y");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 18, 18, 18);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      try { 
        library0.extend("uyzt2p=L", "uyzt2p=L");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot extend on the same day borrowed
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 1, 1287, 1);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      List<String> list0 = library0.availableTitles();
      assertFalse(list0.contains("uyzt2p=L"));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine((String) null, 640, 2, 56000);
      List<String> list0 = library0.availableTitles();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 44, 44, 44);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      try { 
        library0.borrow("uyzt2p=L", "uyzt2p=L");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot borrow more documents
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 1, 478, 1);
      try { 
        library0.borrow("Q@olm'mc", "uyzt2p=L");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.borrow("uyzt2p=L", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find document to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("uyzt2p=L", 1, 1287, 1);
      library0.addStudentMember("uyzt2p=L", "uyzt2p=L");
      library0.borrow("uyzt2p=L", "uyzt2p=L");
      library0.returnDocument("uyzt2p=L", "uyzt2p=L");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addReference("ir.ramtung.impl1.Member", (-538));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Negative or zero copies of a document cannot be added
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember((String) null);
      library0.addMagazine("%syz2{L", 2, 2, 2);
      library0.borrow((String) null, "%syz2{L");
      library0.addStudentMember("%syz2{L", "%syz2{L");
      library0.borrow("%syz2{L", "%syz2{L");
      try { 
        library0.borrow("%syz2{L", "%syz2{L");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document is not available to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }
}
